version: sintr-worker-3
runtime: custom
vm: true
api_version: 1

resources:
  cpu: 1
  memory_gb: 3

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 12
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

skip_files:
- ^.*/packages.*$
- ^.*\.dart$
- ^\.git/.*$
