name: sintr_worker
description: Worker code for sintr
version: 0.0.1
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  appengine: any
  googleapis_auth: '>=0.1.1 <0.3.0'
  gcloud: '>=0.2.0+4 <0.3.0'
  logging: '>=0.11.1 <0.12.0'
  sintr_common:
    git:
      url: git://github.com/lukechurch/sintr_common.git
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
